name: HW2

on:
  push:
    branches: [ test-workflow ]
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Cache
      uses: actions/cache@v1
      env:
        cache-name: stack-cache
      with:
        path: /home/runner/.stack
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.stack') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Run tests
      run: stack test hw2
