name: HW2

on:
  push:
    branches: [ test-workflow ]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Cache
      uses: actions/cache@v1
      env:
        cache-name: stack-cache
      with:
        path: .stack-work
        key: stack

    - name: Run tests
      run: stack test hw2
